{{ if and .Values.ingress.enabled .Values.certificate.enabled -}}
{{- $fullName := include "memos.fullname" . -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "memos.labels" . | nindent 4 }}
spec:
  secretName: {{ $fullName }}-tls
  issuerRef:
    kind: {{ .Values.certificate.issuer.kind }}
    name: {{ .Values.certificate.issuer.name }}
  dnsNames:
  {{- range .Values.ingress.hosts }}
    - {{ .host }}
  {{- end }}
{{- end}}